openapi: 3.1.0
info:
  title: TradingView Screener API - forex
  version: 1.0.0
paths:
  /scan:
    post:
      tags:
      - Scanner
      summary: Run a screener scan
      description: Query TradingView screener and return matching rows.
      operationId: scan_scan_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScanRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScanResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ScanRequest:
      properties:
        markets:
          items:
            type: string
          type: array
          title: Markets
          description: Markets to scan, e.g. ``['america']`` or ``['crypto']``.
          default:
          - america
          examples:
          - - america
          - - crypto
        columns:
          items:
            type: string
          type: array
          title: Columns
          description: Columns to include in the response.
          default:
          - name
          - close
          examples:
          - - name
            - close
            - volume
        limit:
          type: integer
          title: Limit
          description: Maximum number of rows to return.
          default: 50
          examples:
          - 10
      type: object
      title: ScanRequest
      description: Request body for the ``/scan`` endpoint.
    ScanResponse:
      properties:
        count:
          type: integer
          title: Count
          description: Total number of records matching the query.
          example: 17580
        data:
          items:
            additionalProperties: true
            type: object
          type: array
          title: Data
          description: List of result rows.
          examples:
          - - close: 127.25
              name: NVDA
              ticker: NASDAQ:NVDA
            - close: 558.7
              name: SPY
              ticker: AMEX:SPY
      type: object
      required:
      - count
      - data
      title: ScanResponse
      description: Response returned by the ``/scan`` endpoint.
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
